name: TimedNameColour
version: ${project.version}
main: me.remainingtoast.namecolour.Main
api-version: 1.16
authors: [ RemainingToast ]
commands:
  namecolour:
    description: Change namecolour
    aliases: ["nc", "namecolor"]
  namecolourcheck:
    aliases: ["ncc", "namecolorcheck"]
    description: Check amount namecolour left
  togglenamecolour:
    aliases: ["togglenamecolor"]
    description: Hide other players namecolour
  addnamecolour:
    aliases: ["addnamecolor"]
    description: Add hours to players namecolour
    permission: namecolour.add
